### ISSUE TITLE
$(this).on is not a function

### ISSUE THREAD

**Issue by zuzelvp** [riklomas/quicksearch#40]
After the merge of Jan 18 I am getting a '$(this).on is not a function' error when running $('input#search').quicksearch('li')

Is it a bug or something I have to change on my side?

**Comment by elard28** [comment]
doesn't works

**Comment by nitriques** [comment]
@elard28 

1. Your comment does not make anybody want to help you.
1. Checkout this fork, which is maintained https://github.com/DeuxHuitHuit/quicksearch
